load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "catch2_glm",
    hdrs = ["catch2_glm.hpp"],
    include_prefix = "dldt/tools/catch2",
    visibility = ["//visibility:public"],
)
