# exports_files(["spirv.bzl"])

cc_binary(
    name = "fix_compilation_commands",
    srcs = ["fix_compilation_commands.cpp"],
    visibility = ["//visibility:public"],
    deps = [
        "@argparse",
        "@fmt",
        "@nlohmannjson",
    ],
)
